all:
	(cd timerLib; make)
	(cd timerLib; make install)
	(cd MusicBox; make)

clean:
	(cd timerLib; make clean)
	(cd MusicBox; make clean)
	rm -rf lib h
load:
	(cd MusicBox; make load)
reset:
	(cd MusicBox; make reset)
