tokenizer.o: tokenizer.c
	gcc -g tokenizer.c -o tokenizer.o
tester.o:
	gcc -g tester.c -o tester.o
historyExec.o: history.c
	gcc -g history.c -o history.o
clean:
	rm -fr *.o *.o.dSYM \#tester.o\# *.c.
